### ISSUE TITLE
Empty crafting = getting copper to silver upgrade item

### ISSUE THREAD

**Issue by InsaanNotFound** [TechnoVisionDev/IronChest#11] opened 2020-12-14 22:47 UTC
How to replicate: place any item in crafting table and take it out. Voila! You now can receive your free copper to silver upgrade. Checked it in REI; it appears that it is a blank recipe that still results in item being craftable every time.

**Comment by TechnoVisionDev** [comment] 2020-12-15 05:45
Thank you for the bug report! After some testing it seems this happens when you use Iron Chests without a mod that includes copper or silver ingots. I will look into this asap and see what the issue is

**Comment by TechnoVisionDev** [comment] 2020-12-15 06:11
Thank you for the bug report! After some testing it seems this happens when you use Iron Chests without a mod that includes copper or silver ingots. I did some investigating and this is unfortunately a bug with Fabric and CottonResources. I have submitted a bug report to the developer and hope to hear back soon. Unfortunately this seems out of my hands for rn :(

**Comment by InsaanNotFound** [comment] 2020-12-15 07:09
Okay, thanks for responding, hope CR dev fixes it soon!

**Comment by TechnoVisionDev** [comment] 2021-07-21 23:28
This issue is now fixed in the upcoming 1.17.1 update

**Closed as completed by TechnoVisionDev** 2021-07-21 23:28 UTC
